export const SIGN_IN_API_SAGA = 'SIGN_IN_API_SAGA'
export const SIGN_IN_API = 'SIGN_IN_API'

export const SIGN_UP_API_SAGA = 'SIGN_UP_API_SAGA'

export const DELETE_ACCOUNT_SAGA = 'DELETE_ACCOUNT_SAGA'

export const EDIT_ACCOUNT_SAGA = 'EDIT_ACCOUNT_SAGA'

export const GET_ALL_PROJECT_SAGA = 'GET_ALL_PROJECT_SAGA' // project category
export const GET_ALL_PROJECT = 'GET_ALL_PROJECT'

export const CREATE_PROJECT_SAGA = 'CREATE_PROJECT_SAGA'

export const GET_PROJECT_SAGA = 'GET_PROJECT_SAGA'
export const GET_PROJECT = 'GET_PROJECT'

export const SEARCH_PROJECT_SAGA = 'SEARCH_PROJECT_SAGA'
export const SEARCH_PROJECT = 'SEARCH_PROJECT'

export const EDIT_PROJECT_SAGA = 'EDIT_PROJECT_SAGA'

export const DELETE_PROJECT_SAGA = 'DELETE_PROJECT_SAGA'

export const GET_USER_SAGA = 'GET_USER_SAGA'
export const GET_USER = 'GET_USER'

export const ASSIGN_USER_PROJECT = 'ASSIGN_USER_PROJECT'

export const DELETE_USER_FROM_PROJECT = 'DELETE_USER_FROM_PROJECT'

export const GET_PROJECT_DETAIL_SAGA = 'GET_PROJECT_DETAIL_SAGA'
export const GET_PROJECT_DETAIL = 'GET_PROJECT_DETAIL'

export const GET_TASK_TYPE_SAGA = 'GET_TASK_TYPE_SAGA'
export const GET_TASK_TYPE = 'GET_TASK_TYPE'

export const GET_PRIORITY_SAGA = 'GET_PRIORITY_SAGA'
export const GET_PRIORITY = 'GET_PRIORITY'

export const GET_STATUS_SAGA = 'GET_STATUS_SAGA'
export const GET_STATUS = 'GET_STATUS'

export const CREATE_TASK_SAGA = 'CREATE_TASK_SAGA'
export const CREATE_TASK = 'CREATE_TASK'

export const GET_TASK_BY_ID_SAGA = 'GET_TASK_BY_ID_SAGA'
export const GET_TASK_BY_ID = 'GET_TASK_BY_ID'

export const UPDATE_TASK_SAGA = 'UPDATE_TASK_SAGA'

export const DELETE_TASK_SAGA = 'DELETE_TASK_SAGA'

export const UPDATE_STATUS_TASK_SAGA = 'UPDATE_STATUS_TASK_SAGA'

export const CREATE_COMMENT_SAGA = 'CREATE_COMMENT_SAGA'
export const DELETE_COMMENT_SAGA = 'DELETE_COMMENT_SAGA'
export const EDIT_COMMENT_SAGA = 'EDIT_COMMENT_SAGA'
